
// AIassistant.cpp: Defines the class behavior of the application
//

#include "pch.h"
#include "framework.h"
#include "AIassistant.h"
#include "AIassistantDlg.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif


// CAIassistantApp

BEGIN_MESSAGE_MAP(CAIassistantApp, CWinApp)
	ON_COMMAND(ID_HELP, &CWinApp::OnHelp)
END_MESSAGE_MAP()


// CAIassistantApp 

CAIassistantApp::CAIassistantApp()
{
	// Support for Restart Manager
	m_dwRestartManagerSupportFlags = AFX_RESTART_MANAGER_SUPPORT_RESTART;

	// TODO: Add construction code here，
	// Place all important initialization in InitInstance
}


// A unique CAIassistantApp object
CAIassistantApp theApp;


// CAIassistantApp 

BOOL CAIassistantApp::InitInstance()
{
	// InitCommonControlsEx() is required on Windows XP if the application
	// Use ComCtl32.dll version 6 or later to enable visualization mode.
	//InitCommonControlsEx() is required. Otherwise, the window cannot be created.
	INITCOMMONCONTROLSEX InitCtrls;
	InitCtrls.dwSize = sizeof(InitCtrls);
	// Set it to include all the
	// Common control class.
	InitCtrls.dwICC = ICC_WIN95_CLASSES;
	InitCommonControlsEx(&InitCtrls);

	CWinApp::InitInstance();


	AfxEnableControlContainer();

	// Create a shell manager in case the dialog contains
	// Any shell tree view control or shell list view control.
	CShellManager *pShellManager = new CShellManager;

	// Activate the "Windows Native" visual manager to enable themes in MFC controls
	CMFCVisualManager::SetDefaultManager(RUNTIME_CLASS(CMFCVisualManagerWindows));

	// Standard initialization
	// If you are not using these features and want to reduce
	// The final executable file size should be reduced by removing the following
	// No specific initialization routines required
	// Change the registry key used to store settings
	// TODO: This string should be modified appropriately.
	// For example, change it to the company or organization name
	SetRegistryKey(_T("Local applications generated by the Application Wizard"));

	CAIassistantDlg dlg;
	m_pMainWnd = &dlg;
	INT_PTR nResponse = dlg.DoModal();
	if (nResponse == IDOK)
	{
		// TODO: 在此放置处理何时用
		//  “确定”来关闭对话框的代码
	}
	else if (nResponse == IDCANCEL)
	{
		// TODO: Place the handle here when using
		//  "Cancel" to close the dialog code
	}
	else if (nResponse == -1)
	{
		TRACE(traceAppMsg, 0, "Warning: Dialog box creation failed, the application will terminate unexpectedly.\n");
		TRACE(traceAppMsg, 0, "Warning: If you are using MFC controls on a dialog box, you cannot #define _AFX_NO_MFC_CONTROLS_IN_DIALOGS.\n");
	}

	// Delete the shell manager created above
	if (pShellManager != nullptr)
	{
		delete pShellManager;
	}

#if !defined(_AFXDLL) && !defined(_AFX_NO_MFC_CONTROLS_IN_DIALOGS)
	ControlBarCleanUp();
#endif

	// Since the dialog box has been closed, this will return FALSE to exit the application.，
	//  Instead of starting the application's message pump.
	return FALSE;
}

